apiVersion: v1
kind: Service
metadata:
  name: coworking-space-microservices
spec:
  selector:
    pp.kubernetes.io/name: coworking-space-microservices
  ports:
  - name: "5050"
    protocol: TCP
    port: 5050
    targetPort: 5050

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-space-microservices
  labels:
    name: coworking-space-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking-space-microservices
  template:
    metadata:
      labels:
        service: coworking-space-microservices
    spec:
      containers:
      - name: operatinalizing-a-cowrking-space-microservice
        image: 787450662237.dkr.ecr.us-east-1.amazonaws.com/coworking-space:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5050
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5050
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
          - secretRef:
              name: my-postgres-db-password
          - configMapRef:
              name: my-postgres-db-configmap
      restartPolicy: Always
